apiVersion: v1
kind: Service
metadata:
  name: jenkins-patrik
spec:
  ports:
  - port: 8080
    name: webui
  - port: 50000
    name: agent-request
  selector:
    app: jenkins-patrik
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-patrik-home-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jenkins-patrik
spec:
  selector:
    matchLabels:
      app: jenkins-patrik
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins-patrik
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - image: jenkins/jenkins:2.150.1
        name: jenkins-patrik
        ports:
        - containerPort: 50000
          name: agent-request
        - containerPort: 8080
          name: webui
        volumeMounts:
        - name: jenkins-persistent-storage
          mountPath: /var/jenkins_home/
      volumes:
      - name: jenkins-persistent-storage
        persistentVolumeClaim:
          claimName: jenkins-patrik-home-claim
